deps: Allow symfony 7
overblog/GraphiQLBundle pull request #40
Opened 2023-12-09 12:00 UTC by aszenz

Remove sensio it's deprecated

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documented?   | no
| Fixed tickets | https://github.com/overblog/GraphiQLBundle/issues/39
| License       | MIT

Allow symfony 7

2024-02-13 10:20 UTC, grzybu approved these changes

2024-02-20 09:44 UTC, mcg-web requested changes
Thank you @aszenz! Can you fix this one please?

2024-02-20 09:44 UTC, mcg-web commented on composer.json
> +        "symfony/routing": "^5.3.7 || ^6. || ^7.00"
```suggestion
        "symfony/routing": "^5.3.7 || ^6.0 || ^7.00"
```

2024-04-17 10:58 UTC, Dipesh79 commented
@mcg-web can you please new PRs. I need this is symfony 7 project. Can you please review new PRs and merge it?

2024-05-16 07:39 UTC, aat-antoine commented
Like @Dipesh79 said, @mcg-web can you review/merge the PR ?
Merci

2024-05-16 07:54 UTC, mcg-web submitted a review, later dismissed

2024-11-15 14:40 UTC, enricobono commented
Hello @mcg-web. 
In our company we use this library and we'd like to help in making the lib compatible with Symfony 7.
This PR seems to solve the problem. Do you need help with the review? Can we help in any way? :)

2024-11-15 14:52 UTC, mcg-web approved these changes

2024-11-15 14:52 UTC, merged

2024-11-15 15:04 UTC, enricobono commented
Thanks @mcg-web 🙌 

I guess this will unlock https://github.com/thecodingmachine/graphqlite-bundle/issues/206 too ;)